// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/follow/proto/build_event.proto

package proto_build_event

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// A BuildResultStatus describes what has just happened in the event.
type BuildResultStatus int32

const (
	// Build result is unknown. In normal operation this is never set.
	BuildResultStatus_Unknown BuildResultStatus = 0
	// Please is beginning to parse a package.
	BuildResultStatus_PackageParsing BuildResultStatus = 1
	// The package has been parsed successfully.
	BuildResultStatus_PackageParsed BuildResultStatus = 2
	// The package has been parsed, but it failed.
	BuildResultStatus_ParseFailed BuildResultStatus = 3
	// Please has started building a target.
	BuildResultStatus_TargetBuilding BuildResultStatus = 4
	// Please has reached a target, and the input flags requested it to stop here
	// i.e. the request was something like plz build --prepare or --shell etc
	//      which precludes continuing to actually build the target.
	//      This is not a failure state.
	BuildResultStatus_TargetBuildStopped BuildResultStatus = 5
	// The target has been successfully built.
	BuildResultStatus_TargetBuilt BuildResultStatus = 6
	// The target was built by retrieving it from the disk, remote or other cache.
	BuildResultStatus_TargetCached BuildResultStatus = 7
	// The build of the target failed.
	BuildResultStatus_TargetBuildFailed BuildResultStatus = 8
	// Please is beginning to test a target.
	BuildResultStatus_TargetTesting BuildResultStatus = 9
	// The target has finished testing and all tests passed.
	BuildResultStatus_TargetTested BuildResultStatus = 10
	// The target has finished testing but some tests failed.
	BuildResultStatus_TargetTestFailed BuildResultStatus = 11
)

var BuildResultStatus_name = map[int32]string{
	0:  "Unknown",
	1:  "PackageParsing",
	2:  "PackageParsed",
	3:  "ParseFailed",
	4:  "TargetBuilding",
	5:  "TargetBuildStopped",
	6:  "TargetBuilt",
	7:  "TargetCached",
	8:  "TargetBuildFailed",
	9:  "TargetTesting",
	10: "TargetTested",
	11: "TargetTestFailed",
}
var BuildResultStatus_value = map[string]int32{
	"Unknown":            0,
	"PackageParsing":     1,
	"PackageParsed":      2,
	"ParseFailed":        3,
	"TargetBuilding":     4,
	"TargetBuildStopped": 5,
	"TargetBuilt":        6,
	"TargetCached":       7,
	"TargetBuildFailed":  8,
	"TargetTesting":      9,
	"TargetTested":       10,
	"TargetTestFailed":   11,
}

func (x BuildResultStatus) String() string {
	return proto.EnumName(BuildResultStatus_name, int32(x))
}
func (BuildResultStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_build_event_35c2b4d2a0dc9923, []int{0}
}

type ServerConfigRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerConfigRequest) Reset()         { *m = ServerConfigRequest{} }
func (m *ServerConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ServerConfigRequest) ProtoMessage()    {}
func (*ServerConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_event_35c2b4d2a0dc9923, []int{0}
}
func (m *ServerConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerConfigRequest.Unmarshal(m, b)
}
func (m *ServerConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerConfigRequest.Marshal(b, m, deterministic)
}
func (dst *ServerConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerConfigRequest.Merge(dst, src)
}
func (m *ServerConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ServerConfigRequest.Size(m)
}
func (m *ServerConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerConfigRequest proto.InternalMessageInfo

type ServerConfigResponse struct {
	// The total number of threads that the server is configured to run.
	NumThreads int32 `protobuf:"varint,1,opt,name=num_threads,json=numThreads" json:"num_threads,omitempty"`
	// The original targets that the server was requested to run.
	OriginalTargets []*BuildLabel `protobuf:"bytes,2,rep,name=original_targets,json=originalTargets" json:"original_targets,omitempty"`
	// True if the server is running tests.
	Tests bool `protobuf:"varint,3,opt,name=tests" json:"tests,omitempty"`
	// True if the server is running test coverage.
	Coverage bool `protobuf:"varint,4,opt,name=coverage" json:"coverage,omitempty"`
	// The most recent event for each server thread.
	// May be shorter than num_threads since some threads may not have had an event yet.
	LastEvents []*BuildEventResponse `protobuf:"bytes,5,rep,name=last_events,json=lastEvents" json:"last_events,omitempty"`
	// The time that the build started, as nanoseconds since 1970.
	StartTime            int64    `protobuf:"varint,6,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerConfigResponse) Reset()         { *m = ServerConfigResponse{} }
func (m *ServerConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ServerConfigResponse) ProtoMessage()    {}
func (*ServerConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_event_35c2b4d2a0dc9923, []int{1}
}
func (m *ServerConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerConfigResponse.Unmarshal(m, b)
}
func (m *ServerConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerConfigResponse.Marshal(b, m, deterministic)
}
func (dst *ServerConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerConfigResponse.Merge(dst, src)
}
func (m *ServerConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ServerConfigResponse.Size(m)
}
func (m *ServerConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerConfigResponse proto.InternalMessageInfo

func (m *ServerConfigResponse) GetNumThreads() int32 {
	if m != nil {
		return m.NumThreads
	}
	return 0
}

func (m *ServerConfigResponse) GetOriginalTargets() []*BuildLabel {
	if m != nil {
		return m.OriginalTargets
	}
	return nil
}

func (m *ServerConfigResponse) GetTests() bool {
	if m != nil {
		return m.Tests
	}
	return false
}

func (m *ServerConfigResponse) GetCoverage() bool {
	if m != nil {
		return m.Coverage
	}
	return false
}

func (m *ServerConfigResponse) GetLastEvents() []*BuildEventResponse {
	if m != nil {
		return m.LastEvents
	}
	return nil
}

func (m *ServerConfigResponse) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

type BuildEventRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildEventRequest) Reset()         { *m = BuildEventRequest{} }
func (m *BuildEventRequest) String() string { return proto.CompactTextString(m) }
func (*BuildEventRequest) ProtoMessage()    {}
func (*BuildEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_event_35c2b4d2a0dc9923, []int{2}
}
func (m *BuildEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildEventRequest.Unmarshal(m, b)
}
func (m *BuildEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildEventRequest.Marshal(b, m, deterministic)
}
func (dst *BuildEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildEventRequest.Merge(dst, src)
}
func (m *BuildEventRequest) XXX_Size() int {
	return xxx_messageInfo_BuildEventRequest.Size(m)
}
func (m *BuildEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuildEventRequest proto.InternalMessageInfo

type BuildEventResponse struct {
	// Internal id of the thread (goroutine, really) that generated this event.
	// These can be used to chain together consecutive events by the same worker.
	// Ids are guaranteed to be allocated sequentially, starting from 0 and are
	// strictly less than num_threads in the corresponding ServerConfigResponse.
	// You aren't necessarily guaranteed to observe events on any or all threads
	// though.
	ThreadId int32 `protobuf:"varint,1,opt,name=thread_id,json=threadId" json:"thread_id,omitempty"`
	// Timestamp of this event, in nanoseconds since the Unix epoch.
	Timestamp int64 `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	// Build label that this event relates to.
	BuildLabel *BuildLabel `protobuf:"bytes,3,opt,name=build_label,json=buildLabel" json:"build_label,omitempty"`
	// Status of the build.
	Status BuildResultStatus `protobuf:"varint,4,opt,name=status,enum=proto.build_event.BuildResultStatus" json:"status,omitempty"`
	// Error, only populated for failure statuses.
	Error string `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
	// Description of what's going on.
	Description string `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	// If the target was a test, this will contain the results of it.
	TestResults *TestSuite `protobuf:"bytes,7,opt,name=test_results,json=testResults" json:"test_results,omitempty"`
	// Labels of the target
	Labels []string `protobuf:"bytes,8,rep,name=labels" json:"labels,omitempty"`
	// Number of tasks that are currently "activated", i.e. to be done before the build ends.
	// These are somewhat nebulously defined but can provide a measure of progress, as long as
	// you don't mind this number increasing through the build, tasks taking wildly different
	// amounts of time, and that there isn't a 1:1 correspondence between tasks and these messages.
	NumActive int64 `protobuf:"varint,9,opt,name=num_active,json=numActive" json:"num_active,omitempty"`
	// Number of tasks that have been completed so far.
	NumDone              int64    `protobuf:"varint,10,opt,name=num_done,json=numDone" json:"num_done,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildEventResponse) Reset()         { *m = BuildEventResponse{} }
func (m *BuildEventResponse) String() string { return proto.CompactTextString(m) }
func (*BuildEventResponse) ProtoMessage()    {}
func (*BuildEventResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_event_35c2b4d2a0dc9923, []int{3}
}
func (m *BuildEventResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildEventResponse.Unmarshal(m, b)
}
func (m *BuildEventResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildEventResponse.Marshal(b, m, deterministic)
}
func (dst *BuildEventResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildEventResponse.Merge(dst, src)
}
func (m *BuildEventResponse) XXX_Size() int {
	return xxx_messageInfo_BuildEventResponse.Size(m)
}
func (m *BuildEventResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildEventResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuildEventResponse proto.InternalMessageInfo

func (m *BuildEventResponse) GetThreadId() int32 {
	if m != nil {
		return m.ThreadId
	}
	return 0
}

func (m *BuildEventResponse) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BuildEventResponse) GetBuildLabel() *BuildLabel {
	if m != nil {
		return m.BuildLabel
	}
	return nil
}

func (m *BuildEventResponse) GetStatus() BuildResultStatus {
	if m != nil {
		return m.Status
	}
	return BuildResultStatus_Unknown
}

func (m *BuildEventResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *BuildEventResponse) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BuildEventResponse) GetTestResults() *TestSuite {
	if m != nil {
		return m.TestResults
	}
	return nil
}

func (m *BuildEventResponse) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *BuildEventResponse) GetNumActive() int64 {
	if m != nil {
		return m.NumActive
	}
	return 0
}

func (m *BuildEventResponse) GetNumDone() int64 {
	if m != nil {
		return m.NumDone
	}
	return 0
}

type BuildLabel struct {
	PackageName          string   `protobuf:"bytes,1,opt,name=package_name,json=packageName" json:"package_name,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuildLabel) Reset()         { *m = BuildLabel{} }
func (m *BuildLabel) String() string { return proto.CompactTextString(m) }
func (*BuildLabel) ProtoMessage()    {}
func (*BuildLabel) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_event_35c2b4d2a0dc9923, []int{4}
}
func (m *BuildLabel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuildLabel.Unmarshal(m, b)
}
func (m *BuildLabel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuildLabel.Marshal(b, m, deterministic)
}
func (dst *BuildLabel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuildLabel.Merge(dst, src)
}
func (m *BuildLabel) XXX_Size() int {
	return xxx_messageInfo_BuildLabel.Size(m)
}
func (m *BuildLabel) XXX_DiscardUnknown() {
	xxx_messageInfo_BuildLabel.DiscardUnknown(m)
}

var xxx_messageInfo_BuildLabel proto.InternalMessageInfo

func (m *BuildLabel) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *BuildLabel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TestSuite struct {
	// The package name of the test suite.
	Package string `protobuf:"bytes,1,opt,name=package" json:"package,omitempty"`
	// The name of the test suite.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// True if the test results were cached.
	Cached bool `protobuf:"varint,3,opt,name=cached" json:"cached,omitempty"`
	// Duration that the test ran for, in nanoseconds.
	Duration int64 `protobuf:"varint,4,opt,name=duration" json:"duration,omitempty"`
	// True if the test failed due to a timeout.
	TimedOut bool `protobuf:"varint,5,opt,name=timed_out,json=timedOut" json:"timed_out,omitempty"`
	// The test cases that make up this test suite.
	TestCases []*TestCase `protobuf:"bytes,6,rep,name=test_cases,json=testCases" json:"test_cases,omitempty"`
	// Any system properties that were set at the time of execution.
	Properties map[string]string `protobuf:"bytes,7,rep,name=properties" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Timestamp of the start of test execution.
	Timestamp            string   `protobuf:"bytes,8,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestSuite) Reset()         { *m = TestSuite{} }
func (m *TestSuite) String() string { return proto.CompactTextString(m) }
func (*TestSuite) ProtoMessage()    {}
func (*TestSuite) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_event_35c2b4d2a0dc9923, []int{5}
}
func (m *TestSuite) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestSuite.Unmarshal(m, b)
}
func (m *TestSuite) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestSuite.Marshal(b, m, deterministic)
}
func (dst *TestSuite) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestSuite.Merge(dst, src)
}
func (m *TestSuite) XXX_Size() int {
	return xxx_messageInfo_TestSuite.Size(m)
}
func (m *TestSuite) XXX_DiscardUnknown() {
	xxx_messageInfo_TestSuite.DiscardUnknown(m)
}

var xxx_messageInfo_TestSuite proto.InternalMessageInfo

func (m *TestSuite) GetPackage() string {
	if m != nil {
		return m.Package
	}
	return ""
}

func (m *TestSuite) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TestSuite) GetCached() bool {
	if m != nil {
		return m.Cached
	}
	return false
}

func (m *TestSuite) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *TestSuite) GetTimedOut() bool {
	if m != nil {
		return m.TimedOut
	}
	return false
}

func (m *TestSuite) GetTestCases() []*TestCase {
	if m != nil {
		return m.TestCases
	}
	return nil
}

func (m *TestSuite) GetProperties() map[string]string {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *TestSuite) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type TestCase struct {
	// The class name of the test.
	ClassName string `protobuf:"bytes,1,opt,name=class_name,json=className" json:"class_name,omitempty"`
	// The name of the test.
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	// The separate executions that make up this test case.
	TestExecutions       []*TestExecution `protobuf:"bytes,3,rep,name=test_executions,json=testExecutions" json:"test_executions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TestCase) Reset()         { *m = TestCase{} }
func (m *TestCase) String() string { return proto.CompactTextString(m) }
func (*TestCase) ProtoMessage()    {}
func (*TestCase) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_event_35c2b4d2a0dc9923, []int{6}
}
func (m *TestCase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestCase.Unmarshal(m, b)
}
func (m *TestCase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestCase.Marshal(b, m, deterministic)
}
func (dst *TestCase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestCase.Merge(dst, src)
}
func (m *TestCase) XXX_Size() int {
	return xxx_messageInfo_TestCase.Size(m)
}
func (m *TestCase) XXX_DiscardUnknown() {
	xxx_messageInfo_TestCase.DiscardUnknown(m)
}

var xxx_messageInfo_TestCase proto.InternalMessageInfo

func (m *TestCase) GetClassName() string {
	if m != nil {
		return m.ClassName
	}
	return ""
}

func (m *TestCase) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TestCase) GetTestExecutions() []*TestExecution {
	if m != nil {
		return m.TestExecutions
	}
	return nil
}

type TestExecution struct {
	// The failure, if any, from this attempt at running the test.
	Failure *TestFailure `protobuf:"bytes,1,opt,name=failure" json:"failure,omitempty"`
	// The error, if any, from this attempt at running the test.
	Error *TestFailure `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	// The reason for skipping the test, if any.
	Skip *TestSkip `protobuf:"bytes,3,opt,name=skip" json:"skip,omitempty"`
	// Stdout from executing the test.
	Stdout string `protobuf:"bytes,4,opt,name=stdout" json:"stdout,omitempty"`
	// Stderr from executing the test.
	Stderr string `protobuf:"bytes,5,opt,name=stderr" json:"stderr,omitempty"`
	// How long this test took to run (in nanoseconds).
	Duration             int64    `protobuf:"varint,6,opt,name=duration" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestExecution) Reset()         { *m = TestExecution{} }
func (m *TestExecution) String() string { return proto.CompactTextString(m) }
func (*TestExecution) ProtoMessage()    {}
func (*TestExecution) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_event_35c2b4d2a0dc9923, []int{7}
}
func (m *TestExecution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestExecution.Unmarshal(m, b)
}
func (m *TestExecution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestExecution.Marshal(b, m, deterministic)
}
func (dst *TestExecution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestExecution.Merge(dst, src)
}
func (m *TestExecution) XXX_Size() int {
	return xxx_messageInfo_TestExecution.Size(m)
}
func (m *TestExecution) XXX_DiscardUnknown() {
	xxx_messageInfo_TestExecution.DiscardUnknown(m)
}

var xxx_messageInfo_TestExecution proto.InternalMessageInfo

func (m *TestExecution) GetFailure() *TestFailure {
	if m != nil {
		return m.Failure
	}
	return nil
}

func (m *TestExecution) GetError() *TestFailure {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *TestExecution) GetSkip() *TestSkip {
	if m != nil {
		return m.Skip
	}
	return nil
}

func (m *TestExecution) GetStdout() string {
	if m != nil {
		return m.Stdout
	}
	return ""
}

func (m *TestExecution) GetStderr() string {
	if m != nil {
		return m.Stderr
	}
	return ""
}

func (m *TestExecution) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

type TestFailure struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Traceback            string   `protobuf:"bytes,3,opt,name=traceback" json:"traceback,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestFailure) Reset()         { *m = TestFailure{} }
func (m *TestFailure) String() string { return proto.CompactTextString(m) }
func (*TestFailure) ProtoMessage()    {}
func (*TestFailure) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_event_35c2b4d2a0dc9923, []int{8}
}
func (m *TestFailure) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestFailure.Unmarshal(m, b)
}
func (m *TestFailure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestFailure.Marshal(b, m, deterministic)
}
func (dst *TestFailure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestFailure.Merge(dst, src)
}
func (m *TestFailure) XXX_Size() int {
	return xxx_messageInfo_TestFailure.Size(m)
}
func (m *TestFailure) XXX_DiscardUnknown() {
	xxx_messageInfo_TestFailure.DiscardUnknown(m)
}

var xxx_messageInfo_TestFailure proto.InternalMessageInfo

func (m *TestFailure) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TestFailure) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TestFailure) GetTraceback() string {
	if m != nil {
		return m.Traceback
	}
	return ""
}

type TestSkip struct {
	Message              string   `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TestSkip) Reset()         { *m = TestSkip{} }
func (m *TestSkip) String() string { return proto.CompactTextString(m) }
func (*TestSkip) ProtoMessage()    {}
func (*TestSkip) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_event_35c2b4d2a0dc9923, []int{9}
}
func (m *TestSkip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TestSkip.Unmarshal(m, b)
}
func (m *TestSkip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TestSkip.Marshal(b, m, deterministic)
}
func (dst *TestSkip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TestSkip.Merge(dst, src)
}
func (m *TestSkip) XXX_Size() int {
	return xxx_messageInfo_TestSkip.Size(m)
}
func (m *TestSkip) XXX_DiscardUnknown() {
	xxx_messageInfo_TestSkip.DiscardUnknown(m)
}

var xxx_messageInfo_TestSkip proto.InternalMessageInfo

func (m *TestSkip) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ResourceUsageRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceUsageRequest) Reset()         { *m = ResourceUsageRequest{} }
func (m *ResourceUsageRequest) String() string { return proto.CompactTextString(m) }
func (*ResourceUsageRequest) ProtoMessage()    {}
func (*ResourceUsageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_event_35c2b4d2a0dc9923, []int{10}
}
func (m *ResourceUsageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceUsageRequest.Unmarshal(m, b)
}
func (m *ResourceUsageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceUsageRequest.Marshal(b, m, deterministic)
}
func (dst *ResourceUsageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceUsageRequest.Merge(dst, src)
}
func (m *ResourceUsageRequest) XXX_Size() int {
	return xxx_messageInfo_ResourceUsageRequest.Size(m)
}
func (m *ResourceUsageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceUsageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceUsageRequest proto.InternalMessageInfo

type ResourceUsageResponse struct {
	// Total number of CPUs available to the system.
	NumCpus int32 `protobuf:"varint,1,opt,name=num_cpus,json=numCpus" json:"num_cpus,omitempty"`
	// CPU usage that is measured as "in use", excluding I/O, as a percentage.
	CpuUse float64 `protobuf:"fixed64,2,opt,name=cpu_use,json=cpuUse" json:"cpu_use,omitempty"`
	// I/O wait, as a percentage of CPU time.
	IoWait float64 `protobuf:"fixed64,3,opt,name=io_wait,json=ioWait" json:"io_wait,omitempty"`
	// Total amount of memory available
	MemTotal uint64 `protobuf:"varint,4,opt,name=mem_total,json=memTotal" json:"mem_total,omitempty"`
	// Total amount of memory in use.
	MemUsed uint64 `protobuf:"varint,5,opt,name=mem_used,json=memUsed" json:"mem_used,omitempty"`
	// Number of inferior worker processes.
	NumWorkerProcesses   int32    `protobuf:"varint,6,opt,name=num_worker_processes,json=numWorkerProcesses" json:"num_worker_processes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResourceUsageResponse) Reset()         { *m = ResourceUsageResponse{} }
func (m *ResourceUsageResponse) String() string { return proto.CompactTextString(m) }
func (*ResourceUsageResponse) ProtoMessage()    {}
func (*ResourceUsageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_build_event_35c2b4d2a0dc9923, []int{11}
}
func (m *ResourceUsageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceUsageResponse.Unmarshal(m, b)
}
func (m *ResourceUsageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceUsageResponse.Marshal(b, m, deterministic)
}
func (dst *ResourceUsageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceUsageResponse.Merge(dst, src)
}
func (m *ResourceUsageResponse) XXX_Size() int {
	return xxx_messageInfo_ResourceUsageResponse.Size(m)
}
func (m *ResourceUsageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceUsageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceUsageResponse proto.InternalMessageInfo

func (m *ResourceUsageResponse) GetNumCpus() int32 {
	if m != nil {
		return m.NumCpus
	}
	return 0
}

func (m *ResourceUsageResponse) GetCpuUse() float64 {
	if m != nil {
		return m.CpuUse
	}
	return 0
}

func (m *ResourceUsageResponse) GetIoWait() float64 {
	if m != nil {
		return m.IoWait
	}
	return 0
}

func (m *ResourceUsageResponse) GetMemTotal() uint64 {
	if m != nil {
		return m.MemTotal
	}
	return 0
}

func (m *ResourceUsageResponse) GetMemUsed() uint64 {
	if m != nil {
		return m.MemUsed
	}
	return 0
}

func (m *ResourceUsageResponse) GetNumWorkerProcesses() int32 {
	if m != nil {
		return m.NumWorkerProcesses
	}
	return 0
}

func init() {
	proto.RegisterType((*ServerConfigRequest)(nil), "proto.build_event.ServerConfigRequest")
	proto.RegisterType((*ServerConfigResponse)(nil), "proto.build_event.ServerConfigResponse")
	proto.RegisterType((*BuildEventRequest)(nil), "proto.build_event.BuildEventRequest")
	proto.RegisterType((*BuildEventResponse)(nil), "proto.build_event.BuildEventResponse")
	proto.RegisterType((*BuildLabel)(nil), "proto.build_event.BuildLabel")
	proto.RegisterType((*TestSuite)(nil), "proto.build_event.TestSuite")
	proto.RegisterMapType((map[string]string)(nil), "proto.build_event.TestSuite.PropertiesEntry")
	proto.RegisterType((*TestCase)(nil), "proto.build_event.TestCase")
	proto.RegisterType((*TestExecution)(nil), "proto.build_event.TestExecution")
	proto.RegisterType((*TestFailure)(nil), "proto.build_event.TestFailure")
	proto.RegisterType((*TestSkip)(nil), "proto.build_event.TestSkip")
	proto.RegisterType((*ResourceUsageRequest)(nil), "proto.build_event.ResourceUsageRequest")
	proto.RegisterType((*ResourceUsageResponse)(nil), "proto.build_event.ResourceUsageResponse")
	proto.RegisterEnum("proto.build_event.BuildResultStatus", BuildResultStatus_name, BuildResultStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PlzEvents service

type PlzEventsClient interface {
	// Receives information about the state of the server's configuration.
	ServerConfig(ctx context.Context, in *ServerConfigRequest, opts ...grpc.CallOption) (*ServerConfigResponse, error)
	// Receives build events from the remote server.
	BuildEvents(ctx context.Context, in *BuildEventRequest, opts ...grpc.CallOption) (PlzEvents_BuildEventsClient, error)
	// Receives a stream of information about the server's resource usage.
	ResourceUsage(ctx context.Context, in *ResourceUsageRequest, opts ...grpc.CallOption) (PlzEvents_ResourceUsageClient, error)
}

type plzEventsClient struct {
	cc *grpc.ClientConn
}

func NewPlzEventsClient(cc *grpc.ClientConn) PlzEventsClient {
	return &plzEventsClient{cc}
}

func (c *plzEventsClient) ServerConfig(ctx context.Context, in *ServerConfigRequest, opts ...grpc.CallOption) (*ServerConfigResponse, error) {
	out := new(ServerConfigResponse)
	err := grpc.Invoke(ctx, "/proto.build_event.PlzEvents/ServerConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *plzEventsClient) BuildEvents(ctx context.Context, in *BuildEventRequest, opts ...grpc.CallOption) (PlzEvents_BuildEventsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PlzEvents_serviceDesc.Streams[0], c.cc, "/proto.build_event.PlzEvents/BuildEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &plzEventsBuildEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlzEvents_BuildEventsClient interface {
	Recv() (*BuildEventResponse, error)
	grpc.ClientStream
}

type plzEventsBuildEventsClient struct {
	grpc.ClientStream
}

func (x *plzEventsBuildEventsClient) Recv() (*BuildEventResponse, error) {
	m := new(BuildEventResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *plzEventsClient) ResourceUsage(ctx context.Context, in *ResourceUsageRequest, opts ...grpc.CallOption) (PlzEvents_ResourceUsageClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PlzEvents_serviceDesc.Streams[1], c.cc, "/proto.build_event.PlzEvents/ResourceUsage", opts...)
	if err != nil {
		return nil, err
	}
	x := &plzEventsResourceUsageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PlzEvents_ResourceUsageClient interface {
	Recv() (*ResourceUsageResponse, error)
	grpc.ClientStream
}

type plzEventsResourceUsageClient struct {
	grpc.ClientStream
}

func (x *plzEventsResourceUsageClient) Recv() (*ResourceUsageResponse, error) {
	m := new(ResourceUsageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for PlzEvents service

type PlzEventsServer interface {
	// Receives information about the state of the server's configuration.
	ServerConfig(context.Context, *ServerConfigRequest) (*ServerConfigResponse, error)
	// Receives build events from the remote server.
	BuildEvents(*BuildEventRequest, PlzEvents_BuildEventsServer) error
	// Receives a stream of information about the server's resource usage.
	ResourceUsage(*ResourceUsageRequest, PlzEvents_ResourceUsageServer) error
}

func RegisterPlzEventsServer(s *grpc.Server, srv PlzEventsServer) {
	s.RegisterService(&_PlzEvents_serviceDesc, srv)
}

func _PlzEvents_ServerConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlzEventsServer).ServerConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.build_event.PlzEvents/ServerConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlzEventsServer).ServerConfig(ctx, req.(*ServerConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlzEvents_BuildEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildEventRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlzEventsServer).BuildEvents(m, &plzEventsBuildEventsServer{stream})
}

type PlzEvents_BuildEventsServer interface {
	Send(*BuildEventResponse) error
	grpc.ServerStream
}

type plzEventsBuildEventsServer struct {
	grpc.ServerStream
}

func (x *plzEventsBuildEventsServer) Send(m *BuildEventResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _PlzEvents_ResourceUsage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ResourceUsageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PlzEventsServer).ResourceUsage(m, &plzEventsResourceUsageServer{stream})
}

type PlzEvents_ResourceUsageServer interface {
	Send(*ResourceUsageResponse) error
	grpc.ServerStream
}

type plzEventsResourceUsageServer struct {
	grpc.ServerStream
}

func (x *plzEventsResourceUsageServer) Send(m *ResourceUsageResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PlzEvents_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.build_event.PlzEvents",
	HandlerType: (*PlzEventsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServerConfig",
			Handler:    _PlzEvents_ServerConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BuildEvents",
			Handler:       _PlzEvents_BuildEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ResourceUsage",
			Handler:       _PlzEvents_ResourceUsage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "src/follow/proto/build_event.proto",
}

func init() {
	proto.RegisterFile("src/follow/proto/build_event.proto", fileDescriptor_build_event_35c2b4d2a0dc9923)
}

var fileDescriptor_build_event_35c2b4d2a0dc9923 = []byte{
	// 1114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x6d, 0x6f, 0x1b, 0x45,
	0x10, 0xe6, 0x6c, 0xc7, 0xf6, 0xcd, 0xa5, 0xcd, 0x65, 0x9b, 0x96, 0x23, 0x6d, 0xc1, 0x58, 0x05,
	0x2c, 0x84, 0x92, 0x2a, 0xf0, 0xa1, 0xaa, 0x78, 0x11, 0x84, 0x56, 0x54, 0xaa, 0x20, 0xba, 0x24,
	0xaa, 0x90, 0x90, 0x4e, 0x9b, 0xbb, 0x89, 0x7b, 0xf2, 0xbd, 0xb1, 0x2f, 0x09, 0xe1, 0x17, 0xf0,
	0x13, 0x10, 0xbf, 0x82, 0x5f, 0xc2, 0x7f, 0xe1, 0x23, 0x12, 0x1f, 0xd0, 0xec, 0xde, 0xd9, 0xe7,
	0xd6, 0x26, 0xfd, 0xe4, 0x9d, 0x67, 0xe6, 0xd9, 0x99, 0x7d, 0x66, 0x76, 0xcf, 0x30, 0x96, 0x22,
	0xde, 0x3f, 0x2f, 0xb3, 0xac, 0xbc, 0xdc, 0xaf, 0x44, 0xa9, 0xca, 0xfd, 0x33, 0x9d, 0x66, 0x49,
	0x84, 0x17, 0x58, 0xa8, 0x3d, 0x83, 0xb0, 0x6d, 0xf3, 0xb3, 0xd7, 0x72, 0x8c, 0x6f, 0xc3, 0xad,
	0x63, 0x14, 0x17, 0x28, 0x0e, 0xcb, 0xe2, 0x3c, 0x9d, 0x86, 0xf8, 0xb3, 0x46, 0xa9, 0xc6, 0x7f,
	0x74, 0x60, 0x67, 0x19, 0x97, 0x55, 0x59, 0x48, 0x64, 0xef, 0x81, 0x57, 0xe8, 0x3c, 0x52, 0x2f,
	0x05, 0xf2, 0x44, 0x06, 0xce, 0xc8, 0x99, 0x6c, 0x84, 0x50, 0xe8, 0xfc, 0xc4, 0x22, 0xec, 0x3b,
	0xf0, 0x4b, 0x91, 0x4e, 0xd3, 0x82, 0x67, 0x91, 0xe2, 0x62, 0x8a, 0x4a, 0x06, 0x9d, 0x51, 0x77,
	0xe2, 0x1d, 0xdc, 0xdf, 0x7b, 0x2d, 0xfd, 0xde, 0x37, 0xb4, 0x7e, 0xce, 0xcf, 0x30, 0x0b, 0xb7,
	0x1a, 0xda, 0x89, 0x65, 0xb1, 0x1d, 0xd8, 0x50, 0x28, 0x95, 0x0c, 0xba, 0x23, 0x67, 0x32, 0x0c,
	0xad, 0xc1, 0x76, 0x61, 0x18, 0x97, 0x17, 0x28, 0xf8, 0x14, 0x83, 0x9e, 0x71, 0xcc, 0x6d, 0xf6,
	0x14, 0xbc, 0x8c, 0x4b, 0x65, 0xf7, 0x96, 0xc1, 0x86, 0x49, 0xfb, 0xc1, 0xba, 0xb4, 0x4f, 0x68,
	0xd9, 0x1c, 0x2c, 0x04, 0x62, 0x1a, 0x48, 0xb2, 0xfb, 0x00, 0x52, 0x71, 0xa1, 0x22, 0x95, 0xe6,
	0x18, 0xf4, 0x47, 0xce, 0xa4, 0x1b, 0xba, 0x06, 0x39, 0x49, 0x73, 0x1c, 0xdf, 0x82, 0xed, 0xf6,
	0x06, 0x56, 0xb1, 0xdf, 0xbb, 0xc0, 0x5e, 0xdf, 0x96, 0xdd, 0x05, 0xd7, 0x6a, 0x15, 0xa5, 0x49,
	0xad, 0xd6, 0xd0, 0x02, 0xcf, 0x12, 0x76, 0x0f, 0x5c, 0xca, 0x20, 0x15, 0xcf, 0xab, 0xa0, 0x63,
	0xd3, 0xcc, 0x01, 0xf6, 0x25, 0x78, 0xb6, 0xe6, 0x8c, 0xf4, 0x31, 0x2a, 0x5c, 0x2b, 0x22, 0x9c,
	0xcd, 0xd7, 0xec, 0x73, 0xe8, 0x4b, 0xc5, 0x95, 0x96, 0x46, 0xa7, 0x9b, 0x07, 0x0f, 0xd6, 0x51,
	0x43, 0x94, 0x3a, 0x53, 0xc7, 0x26, 0x36, 0xac, 0x39, 0xa4, 0x3e, 0x0a, 0x51, 0x8a, 0x60, 0x63,
	0xe4, 0x4c, 0xdc, 0xd0, 0x1a, 0x6c, 0x04, 0x5e, 0x82, 0x32, 0x16, 0x69, 0xa5, 0xd2, 0xb2, 0x30,
	0xd2, 0xb8, 0x61, 0x1b, 0x62, 0x5f, 0xc1, 0x26, 0x35, 0x2a, 0x12, 0x66, 0x53, 0x19, 0x0c, 0x4c,
	0xd9, 0xf7, 0x56, 0xe4, 0x3e, 0x41, 0xa9, 0x8e, 0x75, 0xaa, 0x30, 0xf4, 0x88, 0x61, 0xab, 0x90,
	0xec, 0x0e, 0xf4, 0xcd, 0x81, 0x65, 0x30, 0x1c, 0x75, 0x27, 0x6e, 0x58, 0x5b, 0xd4, 0x14, 0x9a,
	0x3c, 0x1e, 0xab, 0xf4, 0x02, 0x03, 0xd7, 0xaa, 0x55, 0xe8, 0xfc, 0x6b, 0x03, 0xb0, 0x77, 0x60,
	0x48, 0xee, 0xa4, 0x2c, 0x30, 0x00, 0xe3, 0x1c, 0x14, 0x3a, 0xff, 0xb6, 0x2c, 0x70, 0x7c, 0x08,
	0xb0, 0x90, 0x88, 0xbd, 0x0f, 0x9b, 0x15, 0x8f, 0x67, 0x7c, 0x8a, 0x51, 0xc1, 0x73, 0x34, 0x4d,
	0x71, 0x43, 0xaf, 0xc6, 0xbe, 0xe7, 0x39, 0x32, 0x06, 0x3d, 0xe3, 0xea, 0x18, 0x97, 0x59, 0x8f,
	0xff, 0xee, 0x80, 0x3b, 0xaf, 0x98, 0x05, 0x30, 0xa8, 0x09, 0x35, 0xbf, 0x31, 0x57, 0x71, 0xe9,
	0x48, 0x31, 0x8f, 0x5f, 0x62, 0x52, 0x8f, 0x72, 0x6d, 0xd1, 0x2c, 0x27, 0x5a, 0x70, 0x23, 0x65,
	0xcf, 0xd4, 0x3c, 0xb7, 0xcd, 0xe0, 0xa4, 0x39, 0x26, 0x51, 0xa9, 0x95, 0xe9, 0xc1, 0x30, 0x1c,
	0x1a, 0xe0, 0x07, 0xad, 0xd8, 0x63, 0x00, 0x23, 0x72, 0xcc, 0x25, 0xca, 0xa0, 0x6f, 0xe6, 0xfc,
	0xee, 0x1a, 0x89, 0x0f, 0xb9, 0xc4, 0xd0, 0x55, 0xf5, 0x4a, 0xb2, 0xe7, 0x00, 0x95, 0x28, 0x2b,
	0x14, 0x2a, 0x45, 0x6a, 0x0f, 0x71, 0x3f, 0xf9, 0xbf, 0xf6, 0xec, 0x1d, 0xcd, 0xc3, 0x9f, 0x14,
	0x4a, 0x5c, 0x85, 0x2d, 0xfe, 0xf2, 0x08, 0x0f, 0xcd, 0x99, 0x17, 0xc0, 0xee, 0x17, 0xb0, 0xf5,
	0x0a, 0x99, 0xf9, 0xd0, 0x9d, 0xe1, 0x55, 0xad, 0x1a, 0x2d, 0x69, 0xd2, 0x2e, 0x78, 0xa6, 0x1b,
	0xc9, 0xac, 0xf1, 0xb8, 0xf3, 0xc8, 0x19, 0xff, 0xe6, 0xc0, 0xb0, 0x39, 0x02, 0xf5, 0x3f, 0xce,
	0xb8, 0x94, 0xed, 0xae, 0xb9, 0x06, 0x59, 0xd7, 0x33, 0xf6, 0x0c, 0xb6, 0x8c, 0x4c, 0xf8, 0x0b,
	0xc6, 0x9a, 0x54, 0xa5, 0xb7, 0x84, 0xce, 0x3b, 0x5a, 0x73, 0xde, 0x27, 0x4d, 0x60, 0x78, 0x53,
	0xb5, 0x4d, 0x39, 0xfe, 0xd7, 0x81, 0x1b, 0x4b, 0x11, 0xec, 0x11, 0x0c, 0xce, 0x79, 0x9a, 0x69,
	0x61, 0x8b, 0xf1, 0x0e, 0xde, 0x5d, 0xb3, 0xe9, 0x53, 0x1b, 0x15, 0x36, 0xe1, 0xec, 0xb3, 0xe6,
	0x6a, 0x75, 0xde, 0x88, 0x57, 0x5f, 0xbd, 0x7d, 0xe8, 0xc9, 0x59, 0x5a, 0xd5, 0xef, 0xc0, 0xba,
	0x6e, 0x1f, 0xcf, 0xd2, 0x2a, 0x34, 0x81, 0x34, 0x75, 0x52, 0x25, 0x34, 0x3e, 0x3d, 0xa3, 0x49,
	0x6d, 0xd5, 0x38, 0x8a, 0xe6, 0x6a, 0xd7, 0xd6, 0xd2, 0x34, 0xf6, 0x97, 0xa7, 0x71, 0xfc, 0x23,
	0x78, 0xad, 0x92, 0x48, 0x6c, 0x75, 0x55, 0x35, 0x5d, 0x30, 0x6b, 0xba, 0x12, 0x39, 0x4a, 0x49,
	0x57, 0xc2, 0xf6, 0xa0, 0x31, 0xcd, 0x8c, 0x08, 0x1e, 0xe3, 0x19, 0x8f, 0x67, 0xa6, 0x7c, 0x9a,
	0x91, 0x06, 0x18, 0x3f, 0xb0, 0x3d, 0xa6, 0xc2, 0xdb, 0x7b, 0x38, 0x4b, 0x7b, 0x8c, 0xef, 0xc0,
	0x4e, 0x88, 0xb2, 0xd4, 0x22, 0xc6, 0x53, 0x02, 0x9a, 0x67, 0xf7, 0x2f, 0x07, 0x6e, 0xbf, 0xe2,
	0xa8, 0x5f, 0xde, 0xfa, 0x41, 0x88, 0x2b, 0xdd, 0x7c, 0xa6, 0xe8, 0x41, 0x38, 0xac, 0xb4, 0x64,
	0x6f, 0xc3, 0x20, 0xae, 0x74, 0xa4, 0xa5, 0x2d, 0xd5, 0x09, 0xfb, 0x71, 0xa5, 0x4f, 0x25, 0x92,
	0x23, 0x2d, 0xa3, 0x4b, 0x9e, 0x2a, 0x53, 0xa7, 0x13, 0xf6, 0xd3, 0xf2, 0x05, 0x4f, 0x15, 0xdd,
	0xc6, 0x1c, 0xf3, 0x48, 0x95, 0x8a, 0x67, 0x46, 0xce, 0x5e, 0x38, 0xcc, 0x31, 0x3f, 0x21, 0x9b,
	0x32, 0x91, 0x53, 0x4b, 0x4c, 0x8c, 0xa4, 0x3d, 0x2a, 0x3b, 0x3f, 0x95, 0x98, 0xb0, 0x87, 0xb0,
	0x43, 0x45, 0x5c, 0x96, 0x62, 0x86, 0x22, 0xaa, 0x44, 0x19, 0xa3, 0xb4, 0x57, 0x96, 0x0a, 0x62,
	0x85, 0xce, 0x5f, 0x18, 0xd7, 0x51, 0xe3, 0xf9, 0xf8, 0x1f, 0xa7, 0xfe, 0xba, 0xb4, 0x5f, 0x65,
	0xe6, 0xc1, 0xe0, 0xb4, 0x98, 0x15, 0xe5, 0x65, 0xe1, 0xbf, 0xc5, 0x18, 0xdc, 0x3c, 0xb2, 0xaf,
	0xcd, 0x11, 0x17, 0x32, 0x2d, 0xa6, 0xbe, 0xc3, 0xb6, 0xe1, 0x46, 0x0b, 0xc3, 0xc4, 0xef, 0xb0,
	0x2d, 0xf0, 0xcc, 0x9a, 0x9a, 0x86, 0x89, 0xdf, 0x25, 0x9e, 0xfd, 0xb6, 0x9a, 0xfd, 0x89, 0xd7,
	0x63, 0x77, 0x80, 0xb5, 0xb0, 0x63, 0x55, 0x56, 0x15, 0x26, 0xfe, 0x06, 0x91, 0x17, 0xb8, 0xf2,
	0xfb, 0xcc, 0x87, 0x4d, 0x0b, 0x1c, 0x9a, 0xb7, 0xcb, 0x1f, 0xb0, 0xdb, 0xb0, 0xdd, 0xa2, 0xd6,
	0x59, 0x86, 0x54, 0x89, 0x85, 0xa9, 0xab, 0x94, 0xc4, 0x5d, 0x70, 0x09, 0xc2, 0xc4, 0x07, 0xb6,
	0x03, 0xfe, 0x02, 0xa9, 0xa9, 0xde, 0xc1, 0x9f, 0x1d, 0x70, 0x8f, 0xb2, 0x5f, 0xeb, 0xaf, 0x70,
	0x04, 0x9b, 0xed, 0xbf, 0x20, 0xec, 0xc3, 0x15, 0x23, 0xbf, 0xe2, 0xbf, 0xcb, 0xee, 0x47, 0xd7,
	0xc6, 0xd5, 0x13, 0xf2, 0x13, 0x78, 0x8b, 0x2f, 0xb6, 0x64, 0x0f, 0xae, 0xf9, 0xa3, 0x60, 0x77,
	0x7f, 0xb3, 0xbf, 0x13, 0x0f, 0x1d, 0x96, 0xc0, 0x8d, 0xa5, 0xc1, 0x64, 0xab, 0xea, 0x5a, 0x35,
	0xd3, 0xbb, 0x93, 0xeb, 0x03, 0x9b, 0x2c, 0x67, 0x7d, 0x13, 0xfa, 0xe9, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x59, 0x3a, 0x40, 0xf3, 0xff, 0x09, 0x00, 0x00,
}
